fix: prevent 500 error on archives (#131)
* chore: extend GET_URI_INFO query with conditionals

So that `nextFetchFromWP` can better alter
requests based on the page type.

* chore: add conditionals to getUriInfo service

Exposes isSingular and isArchive in the response.

* chore: update UriInfo type with new conditionals

* chore: update GetUriInfoQuery type

Handled automatically with this command from
packages/headless:

npm run generate-graphql

* refactor: only run getContentNode on singulars

Calling getContentNode on an archive was causing
the 500 error.

* fix: update package-locks

Attempting to clear CI errors.

* revert: remove package locks

* fix: check pageInfo is not void before using

Resolves the compilation error:

Property 'isSingular' does not exist on
type 'void'.

* refactor: improve front page variable name

* refactor: improve inline comment

* refactor: remove unneeded path check

isFrontPage and isPostsPage are all we need.